### PR TITLE
make getResult function public

### PR DESCRIPTION
**Pull request by mimmi20**
I would use your library in one of my projects, but I dont want to use your model. For this I like to make the `getResult` functions public. 

I also fixed some small coding style issues and removed an useless line from the `.php_cs` file (this is overwritten by `concat_with_spaces` in line 45/46).

### CODE REVIEW

**Comment by ThaDafinser** [comment]
Thanks for the PR and sorry for the delay ...were on vacation.

Can't you use the `getProviderResultRaw()` for this use case?
There is the raw result already in.

``` php
$result = $provider->parse('...valid UA');

$result->getProviderResultRaw(); // raw result from each provider
```

You can check the results here (just click on detail of each provider)
http://useragent.mkf.solutions/

**Comment by mimmi20** [comment]
I will check this.

**Comment by mimmi20** [comment]
Could you look on the change in your .php_cs file?

**Comment by ThaDafinser** [comment]
@mimmi20 `.php_cs` change is done. What is with your feedback? Is it enough?

**Comment by mimmi20** [comment]
I am using the `getProviderResultRaw` function now. Thanks.

**Pull request closed without merging**
